packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  core-js: true
  esbuild: true
  msgpackr-extract: false
  msw: true
  protobufjs: true
  sharp: true
  spawn-sync: true

overrides:
  "@types/react": "^19.2.15"
  "@types/react-dom": "^19.2.3"
